- nmigen_boards/alchitry_au.py
Copy-Paste from https://github.com/m-labs/nmigen-boards/pull/44 follows:
Notes:
- Alchitry Au requires a loader program from Alchitry. I tried to follow a pattern similar to what 
nmigen uses to locate Yosys/Vivado but I'm not sure if that's the right approach
- DDR3 is untested. The pins are copied from the schematic so I may have gotten something wrong there.
- There's also an IO shield for the Au with a few buttons, some 7 segment displays, and a bunch of 
LED's. I was debating adding a resource for that, similar to how the icebreaker pmod's are defined, but ultimately decided I was gambling whether I'd finish that pin definition before running out of motivation. Let me know if you'd like that pin definition in this PR and I'll try to add it.
> Add Alchitry Au board definition

- nmigen_boards/nexys4ddr.py
I tested this on a Nexys A7-100T, which as far as I can tell is identical to the Nexys 4 DDR.
> nexys4ddr: Enable pushbutton reset

- nmigen_boards/upduino.py
- nmigen_boards/upduino_v1.py
- nmigen_boards/upduino_v2.py
It's an open-source board which Lattice also sells bundled with a camera module. Design files: https://github.com/gtjennings1/UPDuino_v2_0
The board's oscillator is not connected to the FPGA by default, so this board file relies on support for iCE40 internal oscillators:
https://github.com/nmigen/nmigen/pull/338
> Add a board file for Gnarly Grey's iCE40UP5K 'Upduino' board

- nmigen_boards/blackice.py
- nmigen_boards/blackice_ii.py
- nmigen_boards/de0.py
- nmigen_boards/ice40_hx8k_b_evn.py
- nmigen_boards/icestick.py
- nmigen_boards/nexys4ddr.py
- nmigen_boards/resources/interface.py
This PR adds 'role' parameter to UARTResource and corrects errors and inconsistencies in UART flow control pin definitions.
* icestick: signal names matched the pin numbers, but directions were reversed. Fix by setting role=dce.
* ice40_hx8h_b_evn: RTS/CTS and DTR/DSR pairs were swapped, compared to the schematic, but the direction of DCD was incorrect. Fix by un-swapping, and setting role=dce.
* blackice: no RTS/CTS signals in the schematic (likely was a copy-paste from blackice_ii?), remove corresponding definitions.
* blackice_ii: pin numbers match CH340G signals, but directions were reversed. Fix by setting role=dce.
* de0: RTS/CTS signals match the schematic, but directions were reversed. Fix by setting role=dce.
* nexys4ddr: RTS/CTS signals were swapped compared to the schematic. …
> Add role to UARTResouce and fix UART flow control pin inconsistencies

- nmigen_boards/tinyfpga_ax1.py
- nmigen_boards/tinyfpga_ax2.py
With PR https://github.com/nmigen/nmigen/pull/408 file lattice_machxo2.py is renamed lattice_machxo_2_3l.py.
This PR update tinyfpga_axN classes according to that.
> tinyfpga_axN: use lattice_machxo_2_3l instead of lattice_machxo2

- nmigen_boards/machXO3_sk.py
Hello,
This is the board definition for the Lattice MachX03LF Starter Kit.
Successfully tested  with the blinky example.
Regards,
Gwenhael Goavec-Merou
> Add Lattice MachXO3LF Starter Kit

- nmigen_boards/machXO3_sk.py
This board is based on MachXO3L FPGA. So, replace LatticeMachXO2Platform by LatticeMachXO3LPlatform.
> machXO3_sk: fix platform name

- nmigen_boards/ecp5_5g_evn.py
I left out the QUADSPI mode because I don't have an easy way of testing it at the moment, and I wasn't super confident on how to do it.
> Add SPI Flash, UART, and EXTCLK peripherals to ECP5_EVN

- nmigen_boards/de0_cv.py
Two things were wrong with DE0-CV's SDRAM:  BA and CS.  All other pins were correct.
> fix DE0-CV (bank and cs)

- nmigen_boards/ecpix5.py
This PR provides a separate platform for each ECPIX-5 variant (LFE5UM5G-45F and 85F).
The SD card interface is missing, but will be added later (once we sort out how to integrate it with `SDCardResources`).
The `Blinky` test does nothing currently, because the board does not have user leds, only RGB. We cannot just add some `LEDResources` that share their pins with the RGB leds (like the fomu platforms do), because they rely on a `PULLMODE="up"` constraint, so requesting only one pin would leave the two others unconstrained.
> Add ECPIX-5 support.

- nmigen_boards/orangecrab_r0_2.py
I have not tested this beyond the basic blinky/button test.
>  Add OrangeCrab board.

- nmigen_boards/orangecrab_r0_2.py
With ECP5 IO_TYPE must be used
> orangecrab_r0_2: IO_STANDARD -> IO_TYPE

- nmigen_boards/orangecrab_r0_2.py
This fixes a bad pin definition due to string concatenation with no added space. I figured a long line was better than keeping the split string footgun, but I can redo it with a trailing space if you want to keep to a column width instead.
> orangecrab_r0_2: fix dq pin definitions.

- nmigen_boards/fomu_hacker.py
- nmigen_boards/fomu_pvt.py
- nmigen_boards/orangecrab_r0_1.py
- nmigen_boards/orangecrab_r0_2.py
- nmigen_boards/resources/interface.py
- nmigen_boards/tinyfpga_bx.py
These resource helpers are in the format accepted by e.g. LUNA, and should help to standardize USB pin naming. :)
[Forgive my earlier failure to pull request; I am apparently too tired to use {git, github} properly.]
> add resource helpers for USB (direct+ULPI)

- .github/workflows/main.yml
This should atleast catch trivial typos like #83 and #87.
Currently `nmigen-boards` requires a unreleased version of `nmigen`, so I am manually installing it from git.
> CI: Setup github actions 

- nmigen_boards/orangecrab_r0_2.py
The OrangeCrab ADC utilizes the comparator in the ECP5 A/B pair to do level sensing. This requires "sense_hi"/"sense_lo" to be configured as a diff pair. Consolidate "sense_hi"/"sense_lo" into a diff pair "sense".
> Convert OrangeCrab r0.2 ADC sense to diffpair

- nmigen_boards/orangecrab_r0_2.py
Accidentally merged in OrangeCrab r0.2 board file with broken ADC sense DiffPair. Fixed and tested with my ADC sketch.
> Fix OC r0.2 ADC diffpair

- nmigen_boards/ulx3s.py
Some interesting things about this platform that might be questionable here:
- They use a homebrew microcontroller-based programming method that seems to be supported by a few obscure tools. I've included a `toolchain_program` that uses the tool that seems to be most widely in repos.
- Seems to come with every size of FPGA, so we have four platforms in the same file. This seems cleaner than having four files inheriting from a "default", but this isn't how it's done elsewhere (Versa).
-  The header labeling on the side headers is a little odd on the ULX3S. The left and right headers are treated as one, with consecutive pin numbering; and the pins are labeled deferentially (e.g. `0+`, `0-`, `1+`, `1-`).
> Add ULX3S.

- nmigen_boards/ecpix5.py
Those attributes were present in the LiteX platform file and should be added to nmigen-boards for better signal integrity.
> ecpix5: add termination attributes to DDR3 signals

- nmigen_boards/resources/interface.py
Didn't foresee this when creating the resources: PHYs like the USB3343 have an active-low RST instead of the more typical active-high. Adding a parameter for that.
Also, fixes a typo that affected PHYs with `rst` specified (😳 ).
> resources: allow use of ULPI PHYs with active-low RST pins

- nmigen_boards/versa_ecp5.py
I noticed that the IO types on the versa_ecp5 were wrong, so I copied the ones from Lattice's DDR3 demo.
> versa_ecp5: Fix DDR3 IO types

- nmigen_boards/ecp5_5g_evn.py
- nmigen_boards/ulx3s.py
- nmigen_boards/versa_ecp5.py
This changes several incorrect IO_STANDARD attributes to IO_TYPE.
Signed-off-by: Oguz Meteer <info@guztech.nl>
> Use correct IO attribute for ECP5 FPGAs

- nmigen_boards/arty_s7.py
This is based on Arty A7 file. Some things are handled differently:
* Define "cpu_reset" as default_rst.
* Use openFPGALoader for programming the board.
* Don't overload .bin generation; it does not seem to make a difference.
* Generate also mcs file. This is used by openFPGALoader for programming
into SPI Flash.
Arty S7-50 has been tested on the board by blinky test; Arty S7-25 only
bitstream generation, not on the board.
> Added Arty S7 support

- nmigen_boards/arty_a7.py
The reset button is active-low:
https://reference.digilentinc.com/reference/programmable-logic/arty-a7/reference-manual#basic_io
> Arty A7: Fix `rst` pin polarity

- nmigen_boards/arty_z7.py
fixed those values after checking the official schematics for the arty z7 board
https://reference.digilentinc.com/learn/documentation/schematics/arty-z7-schematic
please check to confirm. the new version works for me, however there might be an oversight I did not notice. this PMOD port is called JB in the schematics.
> fixed PMOD 1 (JB) connections 7-10

- nmigen_boards/ulx3s.py
The boards available on the crowdsupply page, as well as my
hand-built board, all seem to use speed grade 6.
> ulx3s: correct speed grade.

- nmigen_boards/arty_s7.py
This PR does two things:
1. Fixes a typo that prevented the import `from nmigen_boards.arty_s7 import *` from working properly.
2. Adds support for the `openocd` programmer for the Arty S7 board.
I kept in mind your [comments](https://github.com/nmigen/nmigen/issues/428) re: OpenOCD and programmers in general when writing this PR. So perhaps consider it a litmus test to supporting more than one programmer in nmigen :):
>I looked at the openocd invocations currently in nmigen-boards. All of them are different, pretty significantly so. 
Indeed, all the `openocd` invocations are different, and this one's no exception. One difference is that I use the upstream board config file since it's available already (I committed it in mid 2018). Another difference is that I support both JTAG …
> Arty S7 OpenOCD Support

- nmigen_boards/quickfeather.py
This PR introduces two boards which utilize the QuickLogic EOS-S3 platform: https://github.com/nmigen/nmigen/pull/504
The contents are:
- support for QuickFeather board
- support for programming the bitstream using OpenOCD
> Add quickfeather board

- nmigen_boards/te0714_03_50_2I.py
The `SPIFlashResource` defined for this board is connected to the configuration interface, this means one cannot drive the clock directly, but one has to use the `USRCCLKO` primitive. Any guidance on how to reflect this in the platform file?
> Add TE0714-03-50-2l

- nmigen_boards/rz_easyfpga_a2_2.py
This is a relatively cheap FPGA dev board, often found on Aliexpress. It uses the Cyclone IV EP4CE6E22C8.
Some information regarding the pinout was taken from [this repo](https://github.com/jvitkauskas/Altera-Cyclone-IV-board-V3.0).
> Add RZ-EasyFPGA A2.2

- nmigen_boards/ecpix5.py
Also adjust IO_TYPE attribute to match VCCIO which is 1.5v for this board.
This is not a functional change because both SSTL135 and SSTL15 generate identical bitcode.
But it will hopefully prevent some confusion and will match the litex_boards config.
> ecpix-5: ddr3: Add missing address pin.

- nmigen_boards/ulx3s.py
The pin mappings for ring 1 and 2 of the trrs jack were the same.
Fixed with the pinout from [the ulx3s manual](https://github.com/emard/ulx3s/blob/master/doc/constraints/ulx3s_v20.lpf).
> ulx3s: fix pin mapping for audio at ring 2

- nmigen_boards/arty_a7.py
This fixes the following warning:
```
WARNING: [DRC CFGBVS-1] Missing CFGBVS and CONFIG_VOLTAGE Design Properties: Neither the CFGBVS nor CONFIG_VOLTAGE voltage property is set in the current_design.  Configuration bank voltage select (CFGBVS) must be set to VCCO or GND, and CONFIG_VOLTAGE must be set to the correct configuration voltage, in order to determine the I/O voltage support for the pins in bank 0.  It is suggested to specify these either using the 'Edit Device Properties' function in the GUI or directly in the XDC file using the following syntax:
set_property CFGBVS value1 [current_design]
#where value1 is either VCCO or GND
set_property CONFIG_VOLTAGE value2 [current_design]
#where value2 is the voltage provided to configuration bank 0
```
ref: …
> arty_a7: add missing constraints

- nmigen_boards/arty_a7.py
Similar to the Arty S7, the Arty A7 comes in two variants: one with the Xilinx Artix A7 XC7A35TI SKU and the other with the Xilinx Artix A7 XC7A100TI SKU. I have a board with the latter, and ran the Blinky test to be sure that the following commit does not contain any regressions.
Basically the commit follows the same structure as the arty_s7 board by changing `ArtyA7Platform` to `_ArtyA7Platform` and not setting the device constant. Then it introduces `ArtyA7_35Platform` and `ArtyA7_100Platform` for the two different variants, inheriting `_ArtyA7Platform` and setting the device constant to the appropriate SKU for that platform. Finally, the test has been changed to default to running Blinky on the `ArtyA7_35Platform`.
> arty_a7: support both the 35T and 100T SKUs

- nmigen_boards/atlys.py
- nmigen_boards/de0.py
- nmigen_boards/de0_cv.py
- nmigen_boards/mercury.py
- nmigen_boards/nexys4ddr.py
- nmigen_boards/resources/interface.py
- nmigen_boards/rz_easyfpga_a2_2.py
The following FPGAs have one or two PS/2 ports to attach a mouse and keyboard with simply a clock and data signal directly connected to the FPGA:
- Atlys
- DE0
- DE0-CV
- Mercury
- Nexys4DDR
- RZEasyFPGAA2.2
This commit factors out the PS2 resource by defining a function `PS2Resource` that takes the clock signal as `clk` and the data signal as `dat`, and replaces any generic resource using `Resource` with `PS2Resource`.
Boards either use "ps2" or "ps2_host" as a name, and I have used the "ps2" name in `PS2Resource`. We can use the "ps2_host" name instead, but I personally much more prefer the controller/peripheral naming if we do that.
This addresses issue #126.
> Factor out PS2

- nmigen_boards/nandland_go.py
This adds support for the Nandland Go board (https://www.nandland.com/goboard/introduction.html). See also issue #145. The board definition is based on the ICE40HX1KBlinkEVNPlatform for reference, as well as on the [schematic](https://www.nandland.com/goboard/images/Go_Board_V1.pdf) and the [constraints file](https://www.nandland.com/goboard/Go_Board_Constraints.pcf).
Compared to the previous pull request, `import os` and `import subprocess` were missing. The Nandland Go board arrived and I just tested blinky on it to confirm it works.
> nandland_go: add Nandland Go platform.

- nmigen_boards/mercury.py
This commit fixes a regression for the Mercury board caused by a missing `attrs=` when defining the `VGAResource` (see also PR #159).
> mercury: specify attrs key when defining the VGAResource

- nmigen_boards/de10_lite.py
This commit fixes the numbering of the clk50 resources for the DE10 Lite. As the default clock is set to "clk50", it expects "clk50#0" to exist, but the numbering started from 1. In combination with pull request #165, blinky works on the DE10 Lite platform.
> de10_lite: fix clk50 numbering

- nmigen_boards/de10_lite.py
The DE10 Lite board has the Altera MAX10 (10M50DAF484C7G). This commit fixes the package name, because the current name is invalid according to Quartus 14.1 (introduces the MAX10), 18.1 and 20.1.
> de10_lite: fix package SKU name

- nmigen_boards/nandland_go.py
This commit sets `invert=True` for the two 7-segment displays the Nandland Go has, as the signals should be inverted for the 7-segment displays to work properly. I also tested this on the Nandland Go by implementing an 8-bit counter that uses both 7-segment displays to display the current value in hex. I also verified that the DP pin is indeed hardwired to 3V3 instead of being controllable from the FPGA (see [page 2 of the Nandland Go board schematic](https://www.nandland.com/goboard/images/Go_Board_V1.pdf).
> nandland_go: 7seg displays should be inverted

- nmigen_boards/arrow_deca.py
Adds rudimentary support for the Arrow DECA board (see also the user manual) including the clocks, LEDs, switches, buttons and GPIO connectors as well as setitng the correct voltages for the I/O banks. The board features the Intel Altera MAX10 (10M50DAF484C6GES) FPGA.
There are more peripherals like the ADV7513 for HDMI TX, the TI TLV320AIC3254 24-bit audio codec, an SD card reader, etc. but this commit does not add support for those due to the varying voltages required for the different pins in a lot of cases. In addition, I would like to test any further additions thoroughly before committing them :).
To set the I/O bank voltages correctly, and to make sure Quartus doesn't complain (see also Tom Verbeure's blog post), we have to specify some additional set_global_assignment directives …
> arrow_deca: add Arrow DECA platform

- nmigen_boards/arrow_deca.py
The previous PR #158 currently fails to build because I was too slow in fixing this issue that got introduced last-minute. The assignments should be appended to the template for `{{name}}.qsf` that is already provided by `IntelPlatform`. This commit fixes that and ensures that Blinky works for the Arrow DECA.
> arrow_deca: the assignments should be appended to what is originally in the QSF

- nmigen_boards/alchitry_au.py
- nmigen_boards/resources/memory.py
The following commit factors out any instance of the `Resource` function specifying a 'ddr3' resource with a call to `DDR3Resource`. See also issue #15. The following boards have been updated to use `DDR3Resource`:
- Alchitry Au
- Arty A7
- Arty S7
- ECPIX5
- Genesys2
- OrangeCrab r0.1, r0.2
- versa_ecp5, versa_ecp5_5g
As DDR3 uses differential signalling, `DDR3Resource` accepts `diff_attrs` in addition to `attrs`. Some board also specify different attributes for specific pins like the rst, dq and dqs pins.
> Factor out DDR3.

- nmigen_boards/colorlight_5a75b_r7_0.py
Hi I added support for a new board.
Tested with the blinky, button and led just work fine.
Note:
In litex-boards there is an USB connector defined for revision 7.0, I don't believe there such a thing present. 
Would have been nice though :) The pins map to J4 with a 5V level shifter, so not good for USB if not modified.
> Add Colorlight 5A-75B V7.0

- nmigen_boards/extensions/pmod.py
Also fixes PMOD resources to actually work with current nmigen, which does not understand `extras` as a keyword argument to `Resource`.
Note that nmigen-boards requires nmigen 0.2 or newer, and the removal of `extras` came before that release, so I believe this will not break backwards compatibility guarantees (no boards in the repo use the PMOD resources but of course a downstream user might).
> Use positive polarity for SPI chip select in PMOD resources

- nmigen_boards/ebaz4205.py
References:
- https://github.com/fusesoc/blinky/pull/68/files (EBAZ4205 blinky)
- https://github.com/fusesoc/blinky#ebaz4205-development-board
- https://github.com/olofk/serv/pull/59/files (EBAZ4205 'serv' support)
- Existing 'arty_z7.py' example
Usage:
```
$ pwd
nmigen-boards/nmigen_boards
$ pip3 install --editable "."
$ python3 -m nmigen_boards.ebaz4205
```
At this point, both the LEDs should start blinking.
> Add support for EBAZ4205 'Development' Board

- nmigen_boards/orangecrab_r0_1.py
The program pin is incorrect on the OrangeCrab r0.1.
> orangecrab_r0_1: Fix program pin

- amaranth_boards/icebreaker_bitsy.py
This adds:
* The ability to reset the target after bitstream programming.
* The ability to select the Runtime vid:pid that might differ from
project to project.
* The ability to override the default DFU vid:pid if needed.
> icebreaker-bitsy: Increase the programming routine flexibility.

- amaranth_boards/icebreaker_bitsy.py
This corrects the indexing of the edge pins and adds Pmod connectors that are "stacked" onto the edge connector.
The Pmod breakout is a base board that is available for the iCEBreaker-Bitsy and provides a standardized breakout of the edge pins into Pmods. The Pmod index starts at 1 to match the PCB silkscreen.
> Icebitsy pmods

- amaranth_boards/orangecrab_r0_2.py
The newer bootloader on the 85F variant exposes two devices. The first one (0) is the bitstream:
Found DFU: [1209:5af0] ver=0101, devnum=51, cfg=1, intf=0, path="3-1", alt=1, name="0x00100000 RISC-V Firmware", serial="UNKNOWN"
Found DFU: [1209:5af0] ver=0101, devnum=51, cfg=1, intf=0, path="3-1", alt=0, name="0x00080000 Bitstream", serial="UNKNOWN"
See also: https://github.com/orangecrab-fpga/orangecrab-hardware/issues/48
Signed-off-by: Daniel Maslowski <info@orangecms.org>
> orangecrab_r0_2: add `-a 0` to dfu command

- amaranth_boards/orangecrab_r0_2.py
The actual class still had the typo'd name.
> orangecrab_r0_2: fix typo (part 2)

- amaranth_boards/blackice_ii.py
The /CE pin was assigned incorrectly (136 instead of 23), also pin 136 was assigned twice, so the SRAMResource failed to instantiate at all.
Fixed version was tested successfully with HW.
> blackice_ii: fix incorrect SRAM /CE pin assignment

- amaranth_boards/upduino_v3.py
It has the same iCE40UP5k FPGA as the earlier Upduino versions but with an expanded GPIO connector and optional QSPI capability.
> Add a board file for Upduino v3

- .github/workflows/main.yml
- pyproject.toml
Also, expand the Python CI version range to be the same as that of Amaranth.
> Drop support for Python 3.7

- .gitignore
- pyproject.toml
This can simplify smoke testing of boards supported by the FOSS toolchains.
Testing a board with an iCE40, ECP5, etc FPGA is now as simple as:
pdm install --dev
pdm run python -m amaranth_boards.board_name
It is not necessary to install a toolchain, set several environment variables, or do anything else.
> Add PDM development workflow that integrates YoWASP toolchain

- .env.toolchain
- .github/workflows/main.yml
- amaranth_boards/arty_a7.py
- amaranth_boards/de10_nano.py
- amaranth_boards/ice40_hx8k_b_evn.py
- amaranth_boards/ulx3s.py
- amaranth_boards/versa_ecp5.py
- pyproject.toml
The purpose of these tests is just to ensure that Amaranth changes do not blatantly break the boards repository. They are not intended to exhaustively test even a single board.
(The tests currently all fail on Amaranth main branch. This is expected.)
> Add smoke tests for a selection of iCE40, ECP5, Gowin, Xilinx boards

- amaranth_boards/mist.py
This is the original Amiga/Atari ST FPGA board; the predecessor to the MiSTer board.
> Add MiST board.

- .git_archival.txt
- .gitattributes
- .github/workflows/main.yml
- pyproject.toml
- setup.py
Migrate to the PDM build system. Avoids problems with .git_archival.txt breaking reproducibility.
Nabbed from https://github.com/amaranth-lang/amaranth-soc/commit/d66881d83419c689fc96168150e57d9f467723aa
Also take the opportunity to update actions to fix the deprecation warnings.
> Migrate to the PDM build system

- .github/workflows/main.yml
- pyproject.toml
We don't currently plan any changes that will break board definitions in the next release.
> Speculatively mark as compatible with Amaranth 0.6

- amaranth_boards/cmod_s7.py
At the very least, I couldn't get any output from a demo using the UART until I made this change. I think the pins were reversed thanks to a potentially [confusing comment](https://github.com/Digilent/Cmod-S7-25-OOB/blob/master/src/constraints/Cmod-S7-25-Master.xdc#L36-L38) from Digilent's XDC for the board.
> Correct UART pinout for cmod_s7.

- amaranth_boards/stepmxo2.py
Diamond is the default for now; Trellis works in principle. But to make the Trellis flow turnkey requires https://github.com/YosysHQ/prjtrellis/pull/233 to be merged (even in it's current minimal state it should be enough).
There are two variants of this board I'm aware of, but they differ only in how they are programmed, not in peripherals or FPGA; I target the LPC variant, which has a built-in STM32 bootloader that only accepts (a subset of valid) JED files.
All peripherals were tested (and I also tested one GPIO pin).
> Add STEP-MXO2 board support.

- amaranth_boards/machxo2_breakout.py
> Add MachXO2 Breakout board

- amaranth_boards/tang_primer_20k.py
This PR adds support for the [Tang Primer 20k][] Core, Lite, and Dock boards. I compiled the pin assignments from the schematics linked above, from [the vendor's examples][examples], and the [existing LiteX board file][litex]. When sources disagree (and they do!) I preferred the examples, then the schematics.
[Tang Primer 20k]: https://wiki.sipeed.com/hardware/en/tang/tang-primer-20k/primer-20k.html
[examples]: https://github.com/sipeed/TangPrimer-20K-example
[litex]: https://github.com/litex-hub/litex-boards/blob/master/litex_boards/platforms/sipeed_tang_primer_20k.py
The Tang Primer 20k is a SODIMM module that can be optionally socketed into either the Lite board or the Dock board, and all three have different on-board resources. Therefore this PR adds three platforms that share code …
> add support for Tang Primer 20k
